### ISSUE TITLE
Issue with Distribute command after withdraw command

### ISSUE THREAD

**Issue by whitecoder** [K-Singh/ergo-subpooling#1]
Please see the below issues with the distribute command after each miner in the subpool submitted their withdraw request. Any ideas on what would cause the below errors?

$sp-shell.main: load
Standard Config has been file loaded.

Enter "withdraw", "distribute" or "join". Enter "back" to return to main menu.
$sp-shell.load: distribute
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Wallet/Signer testuser was successfully accessed!
Error: There was an issue trying to sign the distribution transaction. Have all miner's sent their withdrawal request?
 ErrorVal: head of empty list
java.util.NoSuchElementException: head of empty list
        at scala.collection.immutable.Nil$.head(List.scala:430)
        at scala.collection.immutable.Nil$.head(List.scala:427)
        at contracts.ConsensusStageHelpers$.$anonfun$findValidInputBoxes$1(ConsensusStageHelpers.scala:138)
        at scala.collection.immutable.List.map(List.scala:286)
        at contracts.ConsensusStageHelpers$.findValidInputBoxes(ConsensusStageHelpers.scala:137)
        at app.AppCommands$.$anonfun$distribute$1(AppCommands.scala:258)
        at app.AppCommands$.$anonfun$distribute$1$adapted(AppCommands.scala:245)
        at org.ergoplatform.appkit.RestApiErgoClient.execute(RestApiErgoClient.java:52)
        at app.AppCommands$.distribute(AppCommands.scala:245)
        at app.AppCommands$.$anonfun$load$3(AppCommands.scala:163)
        at app.AppCommands$.$anonfun$load$3$adapted(AppCommands.scala:156)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at app.AppCommands$.load(AppCommands.scala:156)
        at app.SubPoolingApp$.$anonfun$main$3(SubPoolingApp.scala:52)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at app.SubPoolingApp$.main(SubPoolingApp.scala:43)
        at app.SubPoolingApp.main(SubPoolingApp.scala)
 StackTrace: ()
$sp-shell.load:

**Comment by K-Singh** [comment]
Seems like the consensus address does not have any boxes inside. Can you please try going on https://explorer.ergoplatform.com/en/ and pasting the consensus address into the search bar? Once you've done that, check to make sure that the number of transactions is correct.

The number of transactions should be equal to the number of miners in the subpool. If it is not equal, then the withdraw requests of some of the miners may not have went through. All that means is that those miners will have to send withdraw requests again.

**Comment by whitecoder** [comment]
When I paste the consensus address I'm getting the following error on
explorer.ergoplatform.com/en/. Any ideas? I pulled the address from the
subpool_config.json file that was generated.

Unrecognized search pattern. Please try searching by entering address,
block hash or transaction hash

**Comment by K-Singh** [comment]
Hmm thats very weird then. Do you mind sending me your holding address so that I can check whats on the explorer?
